/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif
#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <folly/Optional.h>
#import <vector>


@protocol MySampleTurboModuleSpec <RCTBridgeModule, RCTTurboModule>

- (NSString *)getString:(NSString *)name;
- (NSArray<NSString *> *)getArray:(NSString *)name;
- (NSDictionary *)getObject:(NSString *)name;
- (void)getPromise:(NSString *)name
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject;
- (void)addListener:(RCTResponseSenderBlock)cb;

@end
namespace facebook {
  namespace react {
    /**
     * ObjC++ class for module 'MySampleTurboModule'
     */
    class JSI_EXPORT MySampleTurboModuleSpecJSI : public ObjCTurboModule {
    public:
      MySampleTurboModuleSpecJSI(
        id<RCTTurboModule> instance,
        std::shared_ptr<CallInvoker> jsInvoker,
        std::shared_ptr<CallInvoker> nativeInvoker,
        id<RCTTurboModulePerformanceLogger> perfLogger);
    };
  } // namespace react
} // namespace facebook

